### ISSUE TITLE
Documentation incorrectly says to use getSigningStrideClient. It should be getSigningStridelabsClient

### ISSUE THREAD

**Issue by kevinstubbs** [cosmology-tech/stridejs#3]
The documentation says we should import `getSigningStrideClient` but actually we need `getSigningStridelabsClient`. To get things working with the currently published npm version, I imported it like this
`import { getSigningStridelabsClient } from 'stridejs/main/codegen/Stridelabs/client'`

**Comment by pyramation** [comment]
updated!

by the way, you can also do 

```js
import { getSigningStridelabsClient } from 'stridejs'
```
